"""update_models_and_timestamps

Revision ID: 760f88a46ab6
Revises: f24509e768f2
Create Date: 2025-09-09 00:08:56.420694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '760f88a46ab6'
down_revision: Union[str, Sequence[str], None] = 'f24509e768f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athletes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=True)
    op.add_column('training_centers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_training_centers_id'), 'training_centers', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_centers_id'), table_name='training_centers')
    op.drop_column('training_centers', 'updated_at')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('athletes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
