"""update_models

Revision ID: f24509e768f2
Revises: 7f7dfb8a1d7b
Create Date: 2025-09-08 23:58:25.032614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24509e768f2'
down_revision: Union[str, Sequence[str], None] = '7f7dfb8a1d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_athletes_id'), 'athletes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athletes_id'), table_name='athletes')
    op.drop_column('athletes', 'updated_at')
    # ### end Alembic commands ###
