version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: workoutapi
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout_db
    ports:
      - "5432:5432"